[package]
name = "images"
version = "0.1.0"
authors = ["ytorii <metalwarrior_type_jp@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22.2"
regex  = "1.3.1"
